[tox]
min_version = 4.0
env_list =
    py313
    py312
    py311
    py310
    format

[testenv]
uv_resolution = lowest-direct
dependency_groups = dev
package = wheel
commands =
    pytest
    mypy

[testenv:format]
dependency_groups = dev
package = wheel
commands =
    ruff format --check ./src ./tests
    ruff check ./src ./tests
